### ISSUE TITLE
How do i turn this into an executable, run the program? Will the there be an executable release?

### ISSUE THREAD

**Issue by souchiika** [kubo25/Diabolik-Lovers-STCM2L-Editor#1]
Hello, im trying to use this editor! ive cloned the repo with git cmd but im unsure on how to run it? I cant find a tutorial on how to compile/build repos (they all lead to a dead end) and im pretty new to all of this, would you help me with it? Im using windows 10 by the way.

**Comment by souchiika** [comment]
I forgot to say, my discord is souchiika#2528 you can dm me on there if youd like

**Comment by kubo25** [comment]
Hi, I've added a release for you. It should just work, but I can't test it because I don't have any of the files anymore.

If you want to take a look at the code, maybe make some changes and compile you only need to download Visual Studio and open 
`Diabolik Lovers STCM2L Editor.sln` in it. This will open the project and in theory you should just be able to press start and it'll work.
